name: BadenTrackerCommit

on:
  push:
    branches: 
      - main

jobs:
  job_on_pr:
    runs-on: labs-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Limpiar y copiar repositorio a /var/www/html
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r . /var/www/html/
